module.exports = [
"[project]/app/helper/notify.tsx [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {

const { jsxDEV: _jsxDEV, Fragment: _Fragment } = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
const React = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
const Notify = ({ text })=>{
    return /*#__PURE__*/ _jsxDEV(_Fragment, {
        children: /*#__PURE__*/ _jsxDEV("div", {
            className: "fixed top-10 mx-auto transition-transform rounded-2xl px-2 py-3 bg-purple-700 text-blue-600",
            children: text
        }, void 0, false, {
            fileName: "[project]/app/helper/notify.tsx",
            lineNumber: 6,
            columnNumber: 5
        }, /*TURBOPACK member replacement*/ __turbopack_context__.e)
    }, void 0, false);
};
module.exports = Notify;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {

const { jsxDEV: _jsxDEV } = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
const React = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
const { Geist, Geist_Mono } = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/font/google/index.js [app-rsc] (ecmascript)");
(()=>{
    throw new Error('could not resolve "' + './globals.css' + '" into a module');
})();
const Notify = __turbopack_context__.r("[project]/app/helper/notify.tsx [app-rsc] (ecmascript)");
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: [
        "latin"
    ]
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: [
        "latin"
    ]
});
const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};
module.exports = metadata;
module.exports = function RootLayout({ children }) {
    return /*#__PURE__*/ _jsxDEV("html", {
        lang: "en",
        children: /*#__PURE__*/ _jsxDEV("body", {
            className: `${geistSans.variable} ${geistMono.variable} antialiased`,
            children: children
        }, void 0, false, {
            fileName: "[project]/app/layout.tsx",
            lineNumber: 30,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/app/layout.tsx",
        lineNumber: 29,
        columnNumber: 5
    }, this);
};
}),
"[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {
"use strict";

module.exports = __turbopack_context__.r("[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/dist/server/route-modules/app-page/module.compiled.js [app-rsc] (ecmascript)").vendored['react-rsc'].ReactJsxDevRuntime; //# sourceMappingURL=react-jsx-dev-runtime.js.map
}),
"[project]/node_modules/.pnpm/next@16.0.10_@babel+core@7.28.5_react-dom@19.2.1_react@19.2.1__react@19.2.1/node_modules/next/font/google/index.js [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {

}),
];

//# sourceMappingURL=_dd83273c._.js.map