import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Notify from "./helper/notify";
import Navbar from "@/components/Navbar";
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#050505] text-white`}>
        <Navbar />
        <main>
          {/* <Notify> */}
          {children}
          {/* </Notify> */}
        </main>
      </body>
    </html>
  );
}
