'use client'
import React from 'react';
import Link from 'next/link';
import { RiFileCopyLine } from 'react-icons/ri';
import { toast } from 'sonner';

export default function ImproveProfilePage() {
  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast("Copied to clipboard!");
  };

  return (
    <div className="min-h-screen bg-[#F3F2EF] text-[#000000] pb-20 pt-24">
      {/* Hanging Hint Tag */}
      <div className="fixed top-24 right-4 sm:right-8 bg-[#ff2f00] text-white px-4 py-2 rounded-l-full rounded-br-full shadow-lg z-50 animate-bounce cursor-default text-sm sm:text-base font-semibold">
        Copy it and Paste it in your Profile 👇
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Main Profile Layout */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden mb-6 relative">
          
          {/* Banner */}
          <div className="h-32 sm:h-48 bg-gray-300 relative group cursor-pointer">
             <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                <button 
                  onClick={() => handleCopy("Background Banner Image Description: A sleek, professional dark-themed banner showcasing software engineering expertise.")}
                  className="bg-white text-black px-3 py-1 rounded-full text-sm font-medium flex items-center gap-2"
                >
                  <RiFileCopyLine /> Copy Banner Prompt
                </button>
             </div>
             {/* Placeholder for banner image generated by Nano Banana */}
             <div className="w-full h-full bg-gradient-to-r from-gray-800 to-gray-600"></div>
          </div>

          {/* Profile Picture & Heading */}
          <div className="px-6 pb-6 relative">
            <div className="relative -mt-16 sm:-mt-24 mb-4">
               {/* Avatar Placeholder */}
               <div className="w-32 h-32 sm:w-40 sm:h-40 rounded-full border-4 border-white bg-gray-200 overflow-hidden">
                  <div className="w-full h-full bg-gray-400"></div>
               </div>
            </div>

            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
              <div className="flex-1 group relative">
                <h1 className="text-2xl sm:text-3xl font-bold flex items-center gap-2">
                  John Doe
                </h1>
                <p className="text-lg mt-1 text-gray-700 max-w-2xl pr-8">
                  Software Engineer | Building Scalable Web Applications | Generative AI Enthusiast
                </p>
                <button 
                  onClick={() => handleCopy("Software Engineer | Building Scalable Web Applications | Generative AI Enthusiast")}
                  className="absolute top-1/2 right-0 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black p-2"
                  title="Copy Headline"
                >
                  <RiFileCopyLine size={20} />
                </button>
                <p className="text-sm text-gray-500 mt-2">Bengaluru, Karnataka, India</p>
              </div>
            </div>
          </div>
        </div>

        {/* About Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6 group relative">
          <div className="flex justify-between items-center mb-4">
             <h2 className="text-xl font-bold">About</h2>
             <button 
                onClick={() => handleCopy("I am a passionate software engineer with 5 years of experience building scalable web applications. I specialize in Next.js, React, and Node.js. Recently, I've been diving deep into generative AI and integrating LLMs into user-friendly products. I thrive in fast-paced environments and love solving complex problems with clean, efficient code.")}
                className="opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black flex items-center gap-1 text-sm bg-gray-100 px-3 py-1 rounded-md"
              >
                <RiFileCopyLine /> Copy
              </button>
          </div>
          <p className="text-sm text-gray-700 whitespace-pre-line leading-relaxed">
            I am a passionate software engineer with 5 years of experience building scalable web applications. I specialize in Next.js, React, and Node.js. Recently, I've been diving deep into generative AI and integrating LLMs into user-friendly products. 
            {"\n\n"}
            I thrive in fast-paced environments and love solving complex problems with clean, efficient code.
          </p>
        </div>

        {/* Experience Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 group relative">
          <div className="flex justify-between items-center mb-4">
             <h2 className="text-xl font-bold">Experience</h2>
             <button 
                onClick={() => handleCopy("- Developed a high-performance web application using Next.js and Tailwind CSS.\n- Integrated Gemini AI to automate profile reviews, increasing user engagement by 40%.\n- Optimized backend API endpoints in Express.js, reducing latency by 30%.")}
                className="opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black flex items-center gap-1 text-sm bg-gray-100 px-3 py-1 rounded-md"
              >
                <RiFileCopyLine /> Copy
              </button>
          </div>
          
          <div className="flex gap-4">
            <div className="w-12 h-12 bg-gray-200 rounded-md shrink-0"></div>
            <div>
              <h3 className="font-semibold text-base">Senior Software Engineer</h3>
              <p className="text-sm text-gray-700">Tech Innovators Inc. · Full-time</p>
              <p className="text-sm text-gray-500 mb-2">Jan 2023 - Present · 1 yr 3 mos</p>
              <ul className="list-disc pl-5 text-sm text-gray-700 space-y-1">
                <li>Developed a high-performance web application using Next.js and Tailwind CSS.</li>
                <li>Integrated Gemini AI to automate profile reviews, increasing user engagement by 40%.</li>
                <li>Optimized backend API endpoints in Express.js, reducing latency by 30%.</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
