"use client";
import React from "react";
import Link from "next/link";
import { RiFileCopyLine } from "react-icons/ri";
import { toast } from "sonner";
import { useLLMResponseStore } from "../Store/store.llmResponse";
import Loader from "@/components/Loader";
import Markdown from "react-markdown";
import { useRouter } from 'next/navigation';
import Section from "@/components/Section";
import { TbArrowBackUp } from "react-icons/tb";

export default function ImproveProfilePage() {
  const router = useRouter();
  const { data } = useLLMResponseStore();

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast("Copied to clipboard!");
  };

  React.useEffect(() => {
    
    if (data?.message) {
      router.back();
    }
    return;
  }, [data]);

  if (data?.message) {
    return (
      <>
      <Section className={'h-screen'}>
        <div className='w-full h-full'>
        <div className='absolute px-68 mt-4'>
          <button onClick={()=>(router.back())} className='not-md:hidden flex items-center text-sm gap-2 hover:bg-[#ff2f00] border border-[#ff3f00] rounded-full px-3 py-1'><TbArrowBackUp/> Go Back</button>
        </div>
        <div className="h-full w-full flex flex-col gap-4 justify-center items-center">
          <Loader />
          {data["message"]}
        </div>
        </div>
      </Section>
      </>
    );
  }

  return (
    <div className="min-h-screen bg-primary text-[#000000] pb-20 pt-24">
      {/* Hanging Hint Tag */}
      <div className="fixed top-24 right-4 sm:right-8 bg-[#ff2f00] text-white px-4 py-2 rounded-l-full rounded-br-full shadow-lg z-50 animate-bounce cursor-default text-sm sm:text-base font-semibold">
        <div>
        Copy it and Paste it in your Profile 👇
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Main Profile Layout */}
        <div className="bg-white rounded-2xl shadow-sm border border-[#ff3f00] overflow-hidden mb-6 relative">
          {/* Banner */}
          <div className="h-32 sm:h-48 bg-gray-300 relative group cursor-pointer">
            {/* Placeholder for banner image generated by Nano Banana */}
            <div className="w-full h-full flex justify-center items-center bg-gradient-to-r from-gray-800 to-gray-600">
              <p className="focus:outline-none w-fit max-w-140 text-justify text-white decoration-none">
                {data.banner
                  ? data.banner
                  : "Banner should look clean and focused."}
              </p>
              <div className="absolute p-4 inset-0 bg-black/20 transition-opacity flex items-end justify-end">
                <button
                  onClick={() => handleCopy(data?.banner)}
                  className="bg-white  text-black px-3 py-1 rounded-full text-sm font-medium flex items-center gap-2"
                >
                  <RiFileCopyLine /> Copy Banner
                </button>
              </div>
            </div>
          </div>

          {/* Profile Picture & Heading */}
          <div className="px-6 pb-6 relative">
            <div className="relative -mt-16 sm:-mt-24 mb-4">
              {/* Avatar Placeholder */}
              <div className="w-32 h-32 sm:w-40 sm:h-40 rounded-full border-4 border-[#fff] bg-gray-200 overflow-hidden">
                <div className="w-full h-full bg-gray-400">{data.profilePicture}</div>
                <button
                  onClick={() => handleCopy(data.bio)}
                  className="absolute top-1/2 right-0 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black p-2"
                  title="Copy Headline"
                >
                  <RiFileCopyLine size={20} />
                </button>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
              <div className="flex-1 group relative">
                <h1 className="text-lg sm:text-3xl font-bold flex items-center gap-2">
                  Your Name
                </h1>
                <p className="text-sm sm:text-lg mt-1 text-gray-700 max-w-2xl pr-8">
                  {data.bio ? data.bio : "Bio details will be here."}
                </p>
                <button
                  onClick={() => handleCopy(data.bio)}
                  className="absolute top-1/2 right-0 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black p-2"
                  title="Copy Headline"
                >
                  <RiFileCopyLine size={20} />
                </button>
                {/* <p className="text-sm text-gray-500 mt-2">
                  Bengaluru, Karnataka, India
                </p> */}
              </div>
            </div>
          </div>
        </div>

        {/* About Section */}
        <div className="bg-white rounded-lg shadow-sm border border-[#ff2f00] p-6 mb-6 group relative">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold">About</h2>
            <button
              onClick={() => handleCopy(data.about)}
              className="opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black flex items-center gap-1 text-sm bg-gray-100 px-3 py-1 rounded-md"
            >
              <RiFileCopyLine /> Copy
            </button>
          </div>
          <p className="text-sm text-gray-700 whitespace-pre-line leading-relaxed">
            {data.about
              ? data.about
              : `I am a passionate individual focused on building impactful solutions through technology. I enjoy solving real-world problems, learning new tools, and continuously improving my skills. \n\n With a strong interest in development and innovation, I aim to create scalable and user-centric applications. I believe in consistency, smart work, and staying curious. Always open to learning, collaborating, and exploring new opportunities.`}
          </p>
        </div>

        {/* Experience Section */}
        <div className="bg-white rounded-lg shadow-sm border border-[#ff2f00] p-6 group relative">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold">Featured</h2>
            <button
              onClick={() => handleCopy(data.posts)}
              className="opacity-0 group-hover:opacity-100 transition-opacity text-gray-500 hover:text-black flex items-center gap-1 text-sm bg-gray-100 px-3 py-1 rounded-md"
            >
              <RiFileCopyLine /> Copy
            </button>
          </div>

          <div className="flex gap-4">
            <div className="w-12 h-12 bg-gray-200 rounded-md shrink-0"></div>
            <div>
                {data.posts
                  ? data.posts.map((item, idx)=>(
                    <div key={idx}>
                      <Markdown>
                        {item}
                      </Markdown>
                    </div>
                  ))
                  : <Markdown>`**Heading** \n\n Subheading \n\n - points to mention \n\n - another point`</Markdown>}
              {/* <h3 className="font-semibold text-base">
                Senior Software Engineer
              </h3>
              <p className="text-sm text-gray-700">
                Tech Innovators Inc. · Full-time
              </p>
              <p className="text-sm text-gray-500 mb-2">
                Jan 2023 - Present · 1 yr 3 mos
              </p>
              <ul className="list-disc pl-5 text-sm text-gray-700 space-y-1">
                <li>
                  Developed a high-performance web application using Next.js and
                  Tailwind CSS.
                </li>
                <li>
                  Integrated Gemini AI to automate profile reviews, increasing
                  user engagement by 40%.
                </li>
                <li>
                  Optimized backend API endpoints in Express.js, reducing
                  latency by 30%.
                </li>
              </ul> */}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
